// private ["_objetsACharger", "_conteneur"];
// objets à charger
// _objetsACharger = [(_this select 1), (_this select 2), "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "B_Mortar_01_F",
// "Land_BarGate_F",
// "B_static_AA_F",
// "B_static_AT_F",
// "Land_BagFence_Long_F",
// "Land_BagFence_Long_F",
// "Land_BagFence_Long_F",
// "Land_BagFence_Long_F",
// "Land_BagFence_Long_F",
// "TF_NATO_Radio_Crate",
// "Flag_NATO_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_HBarrierBig_F",
// "Land_BagBunker_Small_F",
// "ACE_medicalSupplyCrate",
// "ACE_medicalSupplyCrate",
// "ACE_medicalSupplyCrate",
// "ACE_medicalSupplyCrate_advanced",
// "ACE_medicalSupplyCrate_advanced",
// "ACE_medicalSupplyCrate_advanced",
// "ACE_Box_Misc",
// "ACE_Box_Misc",
// "ACE_Box_Misc"];

// _conteneur = _this select 0;

// nul = [_conteneur, _objetsACharger] execVM "R3F_LOG\USER_FUNCT\auto_load_in_vehicle.sqf";
